name: ⚒️ fix!
description: 수정사항을 추가할 때 사용합니다.
title: "[fix] <제목>"
labels: ["fix"]
body:
- type: textarea
  attributes:
    label: 이슈의 SubTask들을 알려주세요.
    description: 해당 내용의 SubTask를 나열해주세요.
    placeholder: subtask1
  validations:
    required: true
